{{- $replicas := .Values.shards.count | int }}
{{- $global := . }}
{{- $weight := 10 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memstore.fullname" $global }}-proxy
data:
  nutcracker.yml: |
    proxy:
      listen: 0.0.0.0:{{ .Values.proxy.service.port }}
      hash: fnv1a_64
      distribution: ketama
      auto_eject_hosts: true
      timeout: 300
      redis: {{ .Values.shards.isRedis }}
      server_retry_timeout: 2000
      server_failure_limit: 1
      servers:
{{- range $i, $e := until $replicas }}
      - {{ include "memstore.fullname" $global }}-headless-{{ $i }}.{{ include "memstore.fullname" $global }}-headless:{{ $global.Values.shards.service.port }}:{{- $weight }}
{{- if (lt ( add1 $i ) $replicas ) }}{{- end }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memstore.fullname" $global }}-proxy
spec:
  replicas: {{ .Values.proxy.count }}
  selector:
    matchLabels:
      {{- include "memstore.selectorLabels" $global | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        {{- include "memstore.selectorLabels" $global | nindent 8 }}
        app.kubernetes.io/component: proxy
    spec:
      containers:
      - name: {{ .Chart.Name }}-proxy
        image: {{ .Values.proxy.image.repository }}
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        ports:
        - name: client
          containerPort: {{ .Values.proxy.service.port }}
        livenessProbe:
          tcpSocket:
            port: client
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: client
          initialDelaySeconds: 5
          timeoutSeconds: 1
        command:
        - "/usr/local/sbin/nutcracker"
        - "--conf-file=/usr/local/etc/nutcracker.yml"
        volumeMounts:
        - name: etc
          mountPath: /usr/local/etc
          readOnly: true
        resources:
          {{- toYaml .Values.proxy.resources | nindent 12 }}
      volumes:
      - name: etc
        configMap:
          name: {{ include "memstore.fullname" $global }}-proxy
          defaultMode: 0644
