# https://stackoverflow.com/questions/57023084/how-to-get-a-pod-index-inside-a-helm-chart
# https://itnext.io/exposing-statefulsets-in-kubernetes-698730fb92a1
# https://github.com/helm/helm/issues/4982
# https://github.com/helm/helm/issues/1311
# https://dev.to/kaoskater08/building-a-headless-service-in-kubernetes-3bk8
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}-headless
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      name: client
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: shards
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  #externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      name: client
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
