# https://stackoverflow.com/questions/57023084/how-to-get-a-pod-index-inside-a-helm-chart
# https://itnext.io/exposing-statefulsets-in-kubernetes-698730fb92a1
# https://github.com/helm/helm/issues/4982
# https://github.com/helm/helm/issues/1311
# https://dev.to/kaoskater08/building-a-headless-service-in-kubernetes-3bk8
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memstore.fullname" . }}-headless
  labels:
    {{- include "memstore.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.shards.service.port }}
      targetPort: {{ .Values.shards.service.port }}
      name: client
  selector:
    {{- include "memstore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: shards
{{- if .Values.shards.service.enabled }}
{{- $global := . }}
{{- $replicas := $global.Values.shards.count | int }}
{{- range $i := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memstore.fullname" $global }}-shard-{{ $i }}
  labels:
    {{- include "memstore.labels" $global | nindent 4 }}
    app.kubernetes.io/component: shard
spec:
  type: {{ $global.Values.shards.service.type }}
{{- if ne $global.Values.shards.service.type "ClusterIP" }}
  externalTrafficPolicy: Local
{{- end }}
  ports:
    - port: {{ $global.Values.shards.service.port }}
      targetPort: {{ $global.Values.shards.service.port }}
      name: client
  selector:
    {{- include "memstore.selectorLabels" $global | nindent 4 }}
    app.kubernetes.io/component: shards
    statefulset.kubernetes.io/pod-name: {{ include "memstore.fullname" $global }}-headless-{{ $i }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memstore.fullname" . }}
  labels:
    {{- include "memstore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
{{- if ne .Values.proxy.service.type "ClusterIP" }}
  externalTrafficPolicy: Local
{{- end }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: {{ .Values.proxy.service.port }}
      name: client
  selector:
    {{- include "memstore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
