# https://stackoverflow.com/questions/57023084/how-to-get-a-pod-index-inside-a-helm-chart
# https://itnext.io/exposing-statefulsets-in-kubernetes-698730fb92a1
# https://github.com/helm/helm/issues/4982
# https://github.com/helm/helm/issues/1311
{{- $root := . -}}
{{ $nreplicas := $root.Values.replicaCount | int }}
{{ range $podIndex := until $nreplicas -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" $root }}-{{ $podIndex }}
  labels:
    {{- include "redis-cluster.labels" $root | nindent 4 }}
spec:
  type: {{ $root.Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ $root.Values.service.port }}
      targetPort: 6379
      # protocol: TCP
      name: client
    #- port: 16379
    #  targetPort: 16379
    #  # protocol: TCP
    #  name: gossip
  selector:
    {{- include "redis-cluster.selectorLabels" $root | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "redis-cluster.fullname" $root }}-{{ $podIndex }}
{{ end -}}

#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "redis-cluster.fullname" $root }}
#  labels:
#    {{- include "redis-cluster.labels" $root | nindent 4 }}
#spec:
#  type: {{ $root.Values.service.type }}
#  clusterIP: None
#  ports:
#    - port: {{ $root.Values.service.port }}
#      targetPort: 6379
#      # protocol: TCP
#      name: client
#    #- port: 16379
#    #  targetPort: 16379
#    #  # protocol: TCP
#    #  name: gossip
#  selector:
#    {{- include "redis-cluster.selectorLabels" $root | nindent 4 }}
