{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "memstore.serviceAccountName" . }}
  labels:
{{ include "memstore.labels" . | nindent 4 }}
{{- end -}}
