---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-cluster.fullname" . }}
data:
  update-node.sh: |
    #!/bin/sh
{{- if .Values.enableRedisCluster }}
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
{{- end }}
    exec "$@"
  redis.conf: |+
{{- if .Values.enableRedisCluster }}
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
{{- end }}
    appendonly yes
    protected-mode no
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-cluster.fullname" . }}-headless
spec:
  serviceName: {{ include "redis-cluster.fullname" . }}-headless
  replicas: {{ .Values.shards.count }}
  selector:
    matchLabels:
      {{- include "redis-cluster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: shards
  template:
    metadata:
      labels:
        {{- include "redis-cluster.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: shards
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.shards.image.repository }}"
        imagePullPolicy: {{ .Values.shards.image.pullPolicy }}
        ports:
{{- if eq .Values.shards.type "redis" }}
        - name: client
          containerPort: 6379
        - name: gossip
          containerPort: 16379
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
{{- else if eq .Values.shards.type "memcached" }}
        - name: client
          containerPort: 11211
        command: ["memcached"]
{{- end }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
        - name: health
          mountPath: /health
          readOnly: true
        resources:
          {{- toYaml .Values.shards.resources | nindent 12 }}
        {{- if .Values.shards.livenessProbe.enabled }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.shards.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.shards.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.shards.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.shards.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.shards.livenessProbe.failureThreshold }}
          exec:
            command:
            - sh
            - -c
            - /health/ping_liveness.sh {{ .Values.shards.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.shards.readinessProbe.enabled }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.shards.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.shards.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.shards.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.shards.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.shards.readinessProbe.failureThreshold }}
          exec:
            command:
            - sh
            - -c
            - /health/ping_readiness.sh {{ .Values.shards.readinessProbe.timeoutSeconds }}
        {{- end }}
      volumes:
      - name: conf
        configMap:
          name: {{ include "redis-cluster.fullname" . }}
          defaultMode: 0755
      - name: health
        configMap:
          name: {{ include "redis-cluster.fullname" . }}-health
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
