name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release developing charts
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: developing
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Release incubating charts
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: incubating
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

